# Generated by Django 3.2 on 2021-08-03 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_menu_menu_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='nombre',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
